// SPDX-License-Identifier: MIT
/// @file   plugins/links/udp/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `GN_LINK_PLUGIN`
///         macro from `sdk/cpp/link_plugin.hpp`.
///
/// The macro emits the five `gn_plugin_*` exports, the kernel-facing
/// `gn_link_vtable_t`, the `gn.link.udp` extension vtable,
/// and the descriptor table. The implementation class
/// (`UdpLink`) supplies the byte-moving logic and the static
/// capability descriptor; everything else is boilerplate the macro
/// owns.

#include "udp.hpp"

#include <sdk/cpp/link_plugin.hpp>

GN_LINK_PLUGIN(::gn::link::udp::UdpLink, "udp")
